core.exception: Linkify exception types
Since the actual descriptions for the various exceptions lie in the
exceptions' documentation, they should be more discoverable. The functions
themselves may pop up in stack traces.